In [49]:
from __future__ import print_function
import torch
import torchvision
import numpy as np
import time

In [50]:
#initializing a tensor
x = torch.empty(5,3)
#Does not print

In [51]:
#5 x3 Matrix
x = torch.rand(5,3)
x

tensor([[ 0.8645,  0.1637,  0.4263],
        [ 0.2694,  0.1931,  0.1721],
        [ 0.3185,  0.8725,  0.2597],
        [ 0.5716,  0.0681,  0.6741],
        [ 0.5139,  0.2481,  0.2654]])

In [52]:
#Empty Tensor with long dtype
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [53]:
#tensor from data
x = torch.tensor([5,5,3])
print(x)

tensor([ 5,  5,  3])


In [54]:
#new_* methods take in sizes
x = x.new_ones(5,3,dtype = torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [55]:
#Overide dtype and randomize values
x = torch.randn_like(x,dtype =torch.float)
print(x) # Has the same shape as the previous one


tensor([[-0.4609,  0.0854, -0.5425],
        [ 1.4299, -1.6109, -0.3564],
        [ 2.4034, -1.7893, -0.3803],
        [-0.2906, -0.2593,  0.6519],
        [-0.3481, -0.1351, -1.0194]])


In [56]:
#Get its size
print(x.size()) #this is a tuple

torch.Size([5, 3])


In [57]:
#tuple operations
print(x.size()+(1,1))

torch.Size([5, 3, 1, 1])


In [ ]:
#adding different methods
for i in range(10):
    x = torch.rand(100,100,100,100,100)
    y = torch.rand(100,100,100,100,100)
    #Method 1
    start =time.time()
    sum_ = x+y
    end= time.time()
    # print("Method1 \n","Time_Taken: ",end-start,"\n \n",sum_)
    print("Method1 \n","Time_Taken: ",end-start,"\n \n")
    #Method 2
    start = time.time()
    sum_ = torch.add(x,y)
    end = time.time()
    # print("Method2 \n","Time_Taken: ",end-start,"\n \n",sum_)
    print("Method2 \n","Time_Taken: ",end-start,"\n \n")
    #Method 3
    start = time.time()
    result = torch.empty(5,3)
    torch.add(x,y,out=result)
    end = time.time()
    # print("Method3 \n","Time_Taken: ",end-start,"\n \n",result)
    print("Method3 \n","Time_Taken: ",end-start,"\n \n")