In [11]:
from __future__ import print_function
import torch
import torchvision
import numpy as np
import time

In [3]:
#initializing a tensor
x = torch.empty(5,3)
#Does not print

In [4]:
#5 x3 Matrix
x = torch.rand(5,3)
x

tensor([[ 0.1433,  0.5464,  0.7008],
        [ 0.7156,  0.6823,  0.9221],
        [ 0.2897,  0.0290,  0.0586],
        [ 0.5607,  0.9772,  0.7155],
        [ 0.6418,  0.6407,  0.6069]])

In [5]:
#Empty Tensor with long dtype
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [6]:
#tensor from data
x = torch.tensor([5,5,3])
print(x)

tensor([ 5,  5,  3])


In [7]:
#new_* methods take in sizes
x = x.new_ones(5,3,dtype = torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [8]:
#Overide dtype and randomize values
x = torch.randn_like(x,dtype =torch.float)
print(x) # Has the same shape as the previous one


tensor([[-1.7986,  1.2577, -1.4209],
        [-0.9309,  1.4791, -0.4196],
        [-1.7569,  0.2037, -1.5089],
        [ 0.0388,  0.6282,  0.2607],
        [-1.4025, -0.2180, -0.5828]])


In [9]:
#Get its size
print(x.size()) #this is a tuple

torch.Size([5, 3])


In [10]:
#tuple operations
print(x.size()+(1,1))

torch.Size([5, 3, 1, 1])


In [22]:
#adding different methods

x = torch.rand(10000,10000)
y = torch.rand(10000,10000)
#Method 1
start =time.time()
sum_ = x+y
end= time.time()
# print("Method1 \n","Time_Taken: ",end-start,"\n \n",sum_)
print("Method1 \n","Time_Taken: ",end-start,"\n \n")
#Method 2
start = time.time()
sum_ = torch.add(x,y)
end = time.time()
# print("Method2 \n","Time_Taken: ",end-start,"\n \n",sum_)
print("Method2 \n","Time_Taken: ",end-start,"\n \n")
#Method 3
start = time.time()
result = torch.empty(5,3)
torch.add(x,y,out=result)
end = time.time()
# print("Method3 \n","Time_Taken: ",end-start,"\n \n",result)
print("Method3 \n","Time_Taken: ",end-start,"\n \n")
#Method 4
start = time.time()
y.add_(x)
print(y)

Method1 
 Time_Taken:  0.4951479434967041 
 

Method2 
 Time_Taken:  0.41791629791259766 
 

Method3 
 Time_Taken:  0.47773289680480957 
 

